"""Auto-generate the nexi capabilities overlay from live sources of truth.

Sources:
- xnch ``GET /nexi/tools``  → native + bridged tool inventory (authoritative)
- ``~/.xnch/mcp-servers.yaml`` → bridge server inventory fallback
- ``nexi.infra.discovery``     → service topology, policies, live probes

The overlay is written atomically (tmp+rename) and only when content changes, so
``nexi/character/prompt_loader.load_capabilities()`` keeps serving a stable merged
view and audit events fire only on real drift.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx
import yaml

from nexi.character.prompt_loader import get_generated_overlay_path
from nexi.config import settings
from nexi.infra.discovery import (
    InfraSnapshot,
    build_snapshot,
    probe_services,
)

logger = logging.getLogger(__name__)

_HEADER = "# AUTO-GENERATED by nexi/character/capability_builder.py — do not edit."

_BASE_CAPABILITIES = Path(__file__).parent / "capabilities.yaml"

_KNOWN_GROUPS: dict[str, str] = {
    "xnch_memory_": "memory",
    "xnch_fs_": "filesystem",
    "xnch_health": "system",
    "xnch_status": "system",
    "xnch_exec_": "execution",
    "xnch_web_": "web_search",
    "crg_": "code_graph",
    "am_": "agent_memory",
    "doc_": "library_docs",
    "c7_": "library_docs",
}


@dataclass
class ToolInventory:
    native: list[str] = field(default_factory=list)
    bridged: dict[str, dict[str, Any]] = field(default_factory=dict)

    @property
    def all_names(self) -> list[str]:
        names = list(self.native)
        for group in self.bridged.values():
            names.extend(group["tools"])
        return names


@dataclass
class BuildResult:
    capabilities: dict[str, Any]
    changed: bool = False
    error: str | None = None


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _group_for(name: str) -> str:
    for prefix, group in _KNOWN_GROUPS.items():
        if name.startswith(prefix):
            return group
    return "other"


def _group_tools(inventory: ToolInventory) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for name in inventory.native:
        grouped.setdefault(_group_for(name), []).append(name)
    for server, meta in inventory.bridged.items():
        grouped.setdefault(_group_for(meta.get("prefix", f"{server}_")), []).extend(
            meta["tools"]
        )
    return {group: sorted(names) for group, names in grouped.items()}


def _load_base_tools() -> dict[str, list[str]]:
    """Tool lists from the hand-maintained base, used as description template."""
    try:
        data = yaml.safe_load(_BASE_CAPABILITIES.read_text()) or {}
        tools = data.get("tools") or {}
        return {group: list(items) for group, items in tools.items() if items}
    except Exception as exc:
        logger.warning("Failed to load base capabilities for tool merge: %s", exc)
        return {}


def _merge_tools(
    base_tools: dict[str, list[str]],
    inventory: ToolInventory,
) -> dict[str, list[str]]:
    """Base tool descriptions ∪ discovered tool names, per group.

    Newly discovered tools are appended (bare name); known ones keep their
    base description so the prompt never degrades when discovery is partial.
    """
    merged: dict[str, list[Any]] = {
        group: list(items) for group, items in base_tools.items()
    }
    for name in inventory.all_names:
        group = _group_for(name)
        items = merged.setdefault(group, [])
        if not any(name in str(i) for i in items):
            items.append(name)

    out: dict[str, list[Any]] = {}
    for group, items in merged.items():
        deduped: list[Any] = []
        seen: set[str] = set()
        for item in items:
            key = str(item) if not isinstance(item, dict) else str(next(iter(item)))
            if key not in seen:
                seen.add(key)
                deduped.append(item)
        out[group] = deduped
    return out


def _build_tool_routing(grouped: dict[str, list[str]]) -> str:
    rules: list[str] = []
    if "code_graph" in grouped:
        rules.append("Code structure / callers / tests / impact? → crg_* tools")
    if "filesystem" in grouped:
        rules.append("File contents on disk? → xnch_fs_*")
    if "execution" in grouped:
        rules.append("Live service state / systemd / logs? → xnch_exec_run")
    if "memory" in grouped:
        rules.append("Chat episodic recall? → xnch_memory_recall (not am_*)")
    if "agent_memory" in grouped:
        rules.append("Cross-session notes / lessons / work items? → am_memory_*")
    if "web_search" in grouped:
        rules.append("Current events / external docs / CVEs? → xnch_web_search")
    if "library_docs" in grouped:
        rules.append("Library/framework API docs? → doc_* (or c7_* when live Context7 enabled)")
    return "\n".join(rules)


def _build_hosts(snapshot: InfraSnapshot) -> dict[str, Any]:
    hosts: dict[str, Any] = {}
    for host, cfg in snapshot.hosts.items():
        services = {
            svc.name: f"{cfg.get('ip', host)}:{svc.port}"
            for svc in snapshot.services_on(host)
        }
        hosts[host] = {
            "role": cfg.get("role", "service"),
            "label": cfg.get("label", host),
            "services": services,
        }
    return hosts


def _build_filesystem(policies: dict[str, Any]) -> dict[str, Any]:
    fs = policies.get("filesystem") or {}
    return {
        "read_only": fs.get("read_only", True),
        "roots": fs.get("roots", ["/home/x-nch"]),
        "path_prefix": "xnchSystems/",
        "deny_globs": fs.get("deny_globs", []),
    }


async def fetch_tool_inventory(
    xnch_base_url: str | None = None,
    timeout: float = 5.0,
    http_client: httpx.AsyncClient | None = None,
) -> ToolInventory:
    """Fetch the live tool inventory from xnch; falls back to local bridge config."""
    base_url = (xnch_base_url or settings.xnch_base_url).rstrip("/")
    url = f"{base_url}{settings.xnch_tools_endpoint}"
    try:
        client = http_client
        if client is None:
            async with httpx.AsyncClient(timeout=timeout) as c:
                resp = await c.get(url)
        else:
            resp = await client.get(url)
        resp.raise_for_status()
        return _parse_tool_inventory(resp.json())
    except Exception as exc:
        logger.warning("Tool inventory fetch from %s failed (%s); using local config", url, exc)
        return _inventory_from_local_config()


def _parse_tool_inventory(payload: dict[str, Any]) -> ToolInventory:
    inventory = ToolInventory()
    for tool in payload.get("tools") or []:
        name = (tool.get("function") or tool).get("name", "") if isinstance(tool, dict) else ""
        if name.startswith("xnch_"):
            inventory.native.append(name)
    for server in (payload.get("bridge") or {}).get("servers") or []:
        sid = server.get("server_id", "")
        prefix = server.get("tool_prefix") or f"{sid}_"
        # Server-level payload doesn't list tool names; expand from local config.
        local = _inventory_from_local_config().bridged.get(sid, {})
        tools = local.get("tools", [])
        inventory.bridged[sid] = {
            "prefix": prefix,
            "server": sid,
            "connected": bool(server.get("connected")),
            "tools": tools,
        }
    return inventory


def _inventory_from_local_config() -> ToolInventory:
    inventory = ToolInventory()
    cfg = _load_mcp_config(settings.mcp_servers_path)
    for sid, server in cfg.items():
        if not isinstance(server, dict) or not server.get("enabled", True):
            continue
        allow = server.get("allow_tools")
        tools = list(allow) if allow else []
        inventory.bridged[sid] = {
            "prefix": str(server.get("tool_prefix", f"{sid}_")),
            "server": sid,
            "connected": False,
            "tools": sorted(tools),
        }
    return inventory


def _load_mcp_config(path: str | Path) -> dict[str, Any]:
    p = Path(path).expanduser()
    if not p.is_file():
        return {}
    try:
        data = yaml.safe_load(p.read_text()) or {}
        return data.get("servers") or {}
    except Exception as exc:
        logger.warning("Failed to load MCP bridge config %s: %s", p, exc)
        return {}


def build_capabilities(snapshot: InfraSnapshot, inventory: ToolInventory) -> dict[str, Any]:
    """Assemble the generated overlay (only keys the loader merges)."""
    base_tools = _load_base_tools()
    grouped = _merge_tools(base_tools, inventory)
    hosts = _build_hosts(snapshot)
    policies = snapshot.policies
    exec_cfg = policies.get("exec") or {}
    bridge_active = any(meta.get("connected") for meta in inventory.bridged.values())

    routing = _build_tool_routing(grouped)
    if bridge_active:
        routing += (
            "\nMCP bridge is ACTIVE: bridged tools (crg_*, am_*, doc_*, c7_*) are "
            "available; max tool rounds increases to 5."
        )

    return {
        "generated_at": _now_iso(),
        "sources": {
            "tool_inventory": f"{settings.xnch_base_url}{settings.xnch_tools_endpoint}",
            "infra_manifests": str(Path(settings.infra_manifests_path).expanduser()),
            "policies": ["exec-policy.yaml", "fs-policy.yaml"],
        },
        "hosts": hosts,
        "tools": grouped,
        "bridge": {
            "active": bridge_active,
            "servers": {
                sid: {"prefix": meta["prefix"], "connected": meta["connected"]}
                for sid, meta in sorted(inventory.bridged.items())
            },
        },
        "tool_routing": routing,
        "filesystem": _build_filesystem(policies),
        "exec": {
            "timeout_seconds": exec_cfg.get("timeout_seconds", 60),
            "denied_substrings": exec_cfg.get("denied_substrings", []),
        },
        "status": snapshot.status,
    }


def render_overlay(capabilities: dict[str, Any]) -> str:
    body = yaml.safe_dump(capabilities, sort_keys=True, default_flow_style=False)
    return f"{_HEADER}\n{body}"


def write_overlay(path: str | Path, content: str) -> bool:
    """Atomic write; returns True only when the file content changed."""
    target = Path(path).expanduser()
    if target.is_file() and target.read_text() == content:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content)
    tmp.replace(target)
    return True


async def refresh(
    manifest_dir: str | Path | None = None,
    xnch_base_url: str | None = None,
    write: bool = True,
    http_client: httpx.AsyncClient | None = None,
) -> BuildResult:
    """Run the full refresh: topology → tools → probes → render → write."""
    snapshot = build_snapshot(manifest_dir)
    snapshot.status = await probe_services(snapshot, http_client=http_client)
    inventory = await fetch_tool_inventory(
        xnch_base_url=xnch_base_url, http_client=http_client
    )
    capabilities = build_capabilities(snapshot, inventory)
    if not write:
        return BuildResult(capabilities=capabilities)

    content = render_overlay(capabilities)
    try:
        changed = write_overlay(get_generated_overlay_path(), content)
    except OSError as exc:
        logger.error("Failed to write capabilities overlay: %s", exc)
        return BuildResult(capabilities=capabilities, error=str(exc))
    return BuildResult(capabilities=capabilities, changed=changed)
