"""Auto-generate the nexi persona overlay from live sources of truth.

Sources (the "everything in XNCHSYSTEMS" inventory):
- ``nexi/infra/discovery``                → hosts, services, live health probes
- ``xnch GET /nexi/tools`` + mcp config   → native + bridged tool inventory
- ``nexi/config.py`` (live values)        → active inference backend + model
- ``opencode.jsonc`` / ``.opencode.json`` / ``.mcp.json`` → OpenCode MCP servers
- ``skills`` dirs (``.claude/skills``, ``skills/superpowers/skills``) → agent skills
- repo topography                        → packages that make up the system

Unlike the capability overlay, this generator produces the *persona narrative itself*:
it fills the ``persona.yaml`` template (which holds only voice/identity constants and
``{placeholders}``) with a live ``self_model`` so no factual claim is ever hardcoded.

The overlay is written atomically (tmp+rename) and only when content changes, so
``nexi/character/prompt_loader.load_persona()`` keeps rendering a stable merged view.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import httpx
import yaml

from nexi.config import settings
from nexi.adapters.model_router import available_models, routing_summary
from nexi.infra.discovery import (
    InfraSnapshot,
    build_snapshot,
    probe_services,
)

logger = logging.getLogger(__name__)

_HEADER = "# AUTO-GENERATED by nexi/character/persona_builder.py — do not edit."

# Repo root: nexi/character/persona_builder.py -> parents[2] == xnchSystems/
_REPO_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class SelfModel:
    """Structured live self-description of the whole workspace."""

    inference_backend: str = ""
    active_model: str = ""
    hosts: dict[str, str] = field(default_factory=dict)
    services: list[dict[str, Any]] = field(default_factory=list)
    mcp_servers: list[str] = field(default_factory=list)
    skills: list[dict[str, str]] = field(default_factory=list)
    tool_count: int = 0
    repo_packages: list[str] = field(default_factory=list)
    healthy: list[str] = field(default_factory=list)
    down: list[str] = field(default_factory=list)
    backend_health: dict[str, bool] = field(default_factory=dict)
    available_models: list[str] = field(default_factory=list)
    model_routing: str = ""


@dataclass
class PersonaResult:
    self_model: SelfModel
    persona_text: str = ""
    changed: bool = False
    error: str | None = None


class PersonaGenerationError(Exception):
    """Raised when the persona template cannot be rendered against the self-model."""


# ---------------------------------------------------------------------------
# Tolerant JSONC parsing (for opencode.jsonc which carries comments + trailing
# commas and `//` inside URL strings).
# ---------------------------------------------------------------------------

def _strip_jsonc(text: str) -> str:
    out: list[str] = []
    i, n = 0, len(text)
    in_str = False
    esc = False
    while i < n:
        c = text[i]
        if in_str:
            out.append(c)
            if esc:
                esc = False
            elif c == "\\":
                esc = True
            elif c == '"':
                in_str = False
            i += 1
            continue
        if c == '"':
            in_str = True
            out.append(c)
            i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "/":
            while i < n and text[i] != "\n":
                i += 1
            continue
        if c == "/" and i + 1 < n and text[i + 1] == "*":
            i += 2
            while i + 1 < n and not (text[i] == "*" and text[i + 1] == "/"):
                i += 1
            i += 2
            continue
        out.append(c)
        i += 1
    stripped = "".join(out)
    # Drop trailing commas before } or ]
    stripped = re.sub(r",(\s*[}\]])", r"\1", stripped)
    return stripped


def _load_jsonc(path: Path) -> dict[str, Any]:
    raw = path.read_text()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        return json.loads(_strip_jsonc(raw))


# ---------------------------------------------------------------------------
# Introspection sources
# ---------------------------------------------------------------------------

def introspect_opencode(root: Path) -> list[str]:
    """Union of MCP server ids from opencode.jsonc / .opencode.json / .mcp.json."""
    servers: list[str] = []
    for fname in ("opencode.jsonc", ".opencode.json", ".mcp.json"):
        p = root / fname
        if not p.is_file():
            continue
        try:
            data = _load_jsonc(p)
        except Exception as exc:
            logger.warning("Failed to parse %s: %s", p, exc)
            continue
        mcp = data.get("mcpServers") or data.get("mcp") or {}
        if isinstance(mcp, dict):
            servers.extend(mcp.keys())
    seen: set[str] = set()
    out: list[str] = []
    for s in servers:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


def introspect_skills(root: Path) -> list[dict[str, str]]:
    """Scan known skill dirs for name + description (markdown frontmatter)."""
    skills: list[dict[str, str]] = []
    seen: set[str] = set()
    search_dirs = [
        root / ".claude" / "skills",
        root / "skills" / "superpowers" / "skills",
    ]
    for d in search_dirs:
        if not d.is_dir():
            continue
        entries = list(d.glob("*.md")) + list(d.glob("*/SKILL.md"))
        for path in entries:
            meta = _parse_skill_frontmatter(path)
            name = meta.get("name") or path.stem
            if name in seen:
                continue
            seen.add(name)
            skills.append({"name": name, "description": meta.get("description", "")})
    return skills


def _parse_skill_frontmatter(path: Path) -> dict[str, str]:
    try:
        text = path.read_text()
    except Exception:
        return {}
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    block = text[3:end].strip()
    meta: dict[str, str] = {}
    for line in block.splitlines():
        if ":" not in line:
            continue
        key, _, val = line.partition(":")
        meta[key.strip()] = val.strip().strip('"').strip("'")
    return meta


def introspect_repo(root: Path) -> list[str]:
    """Curated top-level package list that makes up the system."""
    packages: list[str] = []
    for entry in sorted(root.iterdir()):
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if (entry / "__init__.py").is_file() or (entry / "pyproject.toml").is_file():
            packages.append(entry.name)
    return packages


async def introspect_backend(
    http_client: httpx.AsyncClient | None = None,
) -> tuple[str, str, dict[str, bool]]:
    """Determine the live inference backend from config + health probes."""
    if settings.opencode_go_api_url:
        backend = f"opencode-go (hosted {settings.model_id})"
    elif settings.vllm_primary_url:
        backend = f"vLLM local ({settings.model_id})"
    else:
        backend = settings.model_id or "unknown"
    model = settings.model_id

    health: dict[str, bool] = {}

    async def probe(url: str, key: str) -> None:
        try:
            if http_client is not None:
                r = await http_client.get(url, timeout=settings.probe_timeout_s)
            else:
                async with httpx.AsyncClient(timeout=settings.probe_timeout_s) as c:
                    r = await c.get(url)
            health[key] = r.status_code < 500
        except Exception:
            health[key] = False

    if settings.vllm_health_url:
        await probe(settings.vllm_health_url, "vllm")
    if settings.opencode_go_api_url:
        await probe(settings.opencode_go_api_url, "opencode-go")

    return backend, model, health


# ---------------------------------------------------------------------------
# Assembly
# ---------------------------------------------------------------------------

def build_self_model(
    snapshot: InfraSnapshot,
    tool_count: int,
    mcp_servers: list[str],
    skills: list[dict[str, str]],
    backend: tuple[str, str, dict[str, bool]],
    repo_packages: list[str],
) -> SelfModel:
    hosts: dict[str, str] = {}
    for host, cfg in snapshot.hosts.items():
        label = cfg.get("label", host)
        ip = cfg.get("ip", "")
        hosts[host] = f"{label} ({ip})" if ip else label

    services = [
        {"name": s.name, "host": s.host, "port": s.port, "status": _service_status(snapshot, s.name)}
        for s in snapshot.services
    ]

    return SelfModel(
        inference_backend=backend[0],
        active_model=backend[1],
        hosts=hosts,
        services=services,
        mcp_servers=mcp_servers,
        skills=skills,
        tool_count=tool_count,
        repo_packages=repo_packages,
        healthy=snapshot.status.get("healthy") or [],
        down=snapshot.status.get("down") or [],
        backend_health=backend[2],
        available_models=available_models(),
        model_routing=routing_summary(),
    )


def _service_status(snapshot: InfraSnapshot, name: str) -> str:
    status = snapshot.status or {}
    if name in (status.get("down") or []):
        return "down"
    if name in (status.get("healthy") or []):
        return "healthy"
    return "unknown"


def _build_template_vars(sm: SelfModel) -> dict[str, Any]:
    hosts_summary = " and ".join(sm.hosts.values()) if sm.hosts else "the cluster"
    mcp_servers = ", ".join(sm.mcp_servers) or "none"
    skill_names = ", ".join(s["name"] for s in sm.skills[:12]) or "none"
    return {
        "inference_backend": sm.inference_backend,
        "active_model": sm.active_model,
        "hosts_summary": hosts_summary,
        "tool_count": sm.tool_count,
        "mcp_servers": mcp_servers,
        "skill_names": skill_names,
        "model_routing": sm.model_routing or "auto-routed per task",
        "live_status": _build_live_status(sm),
    }


def _build_live_status(sm: SelfModel) -> str:
    parts: list[str] = []
    if sm.healthy:
        parts.append(f"{', '.join(sm.healthy)} healthy")
    if sm.down:
        parts.append(f"{', '.join(sm.down)} DOWN")
    if not parts:
        parts.append("status unknown")
    if sm.backend_health:
        for key, ok in sm.backend_health.items():
            parts.append(f"{key} {'up' if ok else 'DOWN'}")
    return "; ".join(parts)


def render_persona_template(template: str, sm: SelfModel) -> str:
    """Fill the persona.yaml template with live self-model values."""
    try:
        return template.format(**_build_template_vars(sm))
    except (KeyError, IndexError) as exc:
        raise PersonaGenerationError(f"Persona template placeholder unresolved: {exc}")


def render_overlay(self_model: SelfModel, generated_at_iso: str) -> str:
    payload = {
        "generated_at": generated_at_iso,
        "self_model": self_model.__dict__,
    }
    body = yaml.safe_dump(payload, sort_keys=True, default_flow_style=False)
    return f"{_HEADER}\n{body}"


def write_persona_overlay(path: str | Path, content: str) -> bool:
    """Atomic write; returns True only when the file content changed."""
    target = Path(path).expanduser()
    if target.is_file() and target.read_text() == content:
        return False
    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(target.suffix + ".tmp")
    tmp.write_text(content)
    tmp.replace(target)
    return True


def get_persona_overlay_path() -> Path:
    return Path(settings.persona_generated_path).expanduser()


async def build_persona(
    write: bool = True,
    http_client: httpx.AsyncClient | None = None,
) -> PersonaResult:
    """Full refresh: topology → tools → backend → skills → repo → render → write."""
    try:
        snapshot = build_snapshot()
        snapshot.status = await probe_services(snapshot, http_client=http_client)

        from nexi.character.capability_builder import fetch_tool_inventory

        inventory = await fetch_tool_inventory(http_client=http_client)
        tool_count = len(inventory.all_names)

        mcp_servers = introspect_opencode(_REPO_ROOT)
        skills = introspect_skills(_REPO_ROOT)
        backend = await introspect_backend(http_client=http_client)
        repo_packages = introspect_repo(_REPO_ROOT)

        sm = build_self_model(snapshot, tool_count, mcp_servers, skills, backend, repo_packages)
        persona_text = render_persona_template(_load_persona_template(), sm)

        if not write:
            return PersonaResult(self_model=sm, persona_text=persona_text)

        content = render_overlay(sm, _now_iso())
        try:
            changed = write_persona_overlay(get_persona_overlay_path(), content)
        except OSError as exc:
            logger.error("Failed to write persona overlay: %s", exc)
            return PersonaResult(self_model=sm, persona_text=persona_text, error=str(exc))

        return PersonaResult(self_model=sm, persona_text=persona_text, changed=changed)
    except Exception as exc:  # surface, never crash the refresh loop
        logger.error("Persona build failed: %s", exc)
        return PersonaResult(self_model=SelfModel(), error=str(exc))


_PERSONA_YAML = Path(__file__).parent / "persona.yaml"

# Fallback template if persona.yaml cannot be read (kept in sync with persona.yaml).
_FALLBACK_TEMPLATE = """You are Nexi, a private AI orchestration intelligence running on ck-san's personal
hardware. You are not a generic assistant. You have continuity — you remember past
sessions, ongoing projects, and ck-san's preferences from memory. You operate through
the xnch control plane; tools and policy live there — you invoke them in chat when needed.
You are:
- Direct: say what you think, don't hedge unless genuinely uncertain
- Technically precise: you know the XNCH stack intimately — your inference backend is
  {inference_backend} serving {active_model}, and you run on {hosts_summary}.
- Proactive: you notice patterns and surface them without being asked
- Loyal: ck-san's goals are your goals. You prioritize privacy, local inference, and
  low-noise environments
- Opinionated: you prefer elegant systems over bloated ones. You will say 'this is
  a bad design' if it is.
- Tool-grounded: when asked about files, config, or live system state, use your
  {tool_count} live tools (MCP servers {mcp_servers}; skills {skill_names}) — do not
  invent contents or status.
LIVE STATUS: {live_status}
"""


def _load_persona_template() -> str:
    """Read the live persona template from persona.yaml (the single source of voice)."""
    try:
        data = yaml.safe_load(_PERSONA_YAML.read_text()) or {}
        return (data.get("identity") or {}).get("persona", "") or _FALLBACK_TEMPLATE
    except Exception as exc:
        logger.warning("Failed to load persona template: %s", exc)
        return _FALLBACK_TEMPLATE


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
